"""界面文本集中管理；语言只影响显示，不改变规则或难度 ID。"""

DEFAULT_LANGUAGE = "en"

TEXT = {
    "en": {
        "title": "ALIEN INVASION",
        "window_title": "Alien Invasion",
        "setup_title": "Mission Setup",
        "settings_title": "Settings",
        "tagline": "Survive 12 waves and defeat the alien mothership",
        "start_game": "Start Game",
        "settings": "Settings",
        "quit": "Quit",
        "easy": "Easy",
        "standard": "Standard",
        "hard": "Hard",
        "start_battle": "Start Mission",
        "menu": "Main Menu",
        "resume": "Resume",
        "restart": "Restart",
        "back": "Back",
        "play_again": "Play Again",
        "retry": "Retry",
        "language": "Language",
        "english": "English",
        "chinese": "简体中文",
        "sfx_volume": "Sound Effects",
        "music_volume": "Music",
        "action_header": "Action",
        "key_header": "Key / Input",
        "action_move_up": "Move Up",
        "action_move_down": "Move Down",
        "action_move_left": "Move Left",
        "action_move_right": "Move Right",
        "action_missile": "Guided Missiles",
        "action_arc": "Chain Arc",
        "action_support": "Fire Support",
        "action_pause": "Pause / Resume",
        "action_aim": "Aim",
        "action_fire": "Fire",
        "mouse_move": "Mouse Movement",
        "mouse_left": "Left Mouse Button",
        "key_prompt": "Press any key...",
        "edit_hint": "Click a key cell, then press a keyboard key.",
        "setup_hint": "Change key bindings in Settings.",
        "conflict_hint": "Shared keys trigger all assigned actions.",
        "reset_keys": "Reset Key Bindings",
        "save_failed": "Could not save settings; changes apply for this run.",
        "bgm_loaded": "Background music loaded",
        "bgm_missing": "No background music provided",
        "audio_unavailable": "Audio device unavailable: sound muted",
        "rule_goal": "Clear 12 waves and defeat the mothership.",
        "rule_health": "Zero health ends the mission.",
        "rule_supplies": "Supplies every 7s; full capacity keeps them.",
        "rule_weapons": "Special weapons: 3 charges, 5s duration.",
        "rule_support": "Full energy: 5 strikes; no recharge during support.",
        "rule_focus": "Focus loss pauses; press fire again after resuming.",
        "boss_status": "MOTHERSHIP  {hp}/{max_hp}  PHASE {phase}",
        "phase_transition": "PHASE TRANSITION",
        "boss_warning": "WARNING - MOTHERSHIP APPROACHING",
        "hp_score": "HP {hp:3}  Score {score}",
        "bullet": "Basic Bullets",
        "missile": "Guided Missiles",
        "arc": "Chain Arc",
        "weapon_status": "{weapon}  {seconds:.1f}s",
        "support_status": "Support {seconds:.1f}s",
        "wave_status": "WAVE {number}/12   {phase}",
        "waves": "ENEMY WAVES",
        "rest": "WAVE BREAK",
        "meteor_clear": "CLEARING METEORS",
        "boss_approach": "BOSS APPROACHING",
        "boss_entry": "BOSS ENTRY",
        "boss_fight": "BOSS FIGHT",
        "paused": "Mission Paused - {binding} to Resume",
        "victory": "Mission Complete",
        "defeat": "Mission Failed",
        "result": "Score {score}  /  Kills {kills}  /  Time {seconds:.1f}s",
    },
    "zh-CN": {
        "title": "外星入侵",
        "window_title": "外星入侵",
        "setup_title": "出击准备",
        "settings_title": "设置",
        "tagline": "生存 · 12 波敌群 · 外星母舰",
        "start_game": "开始游戏",
        "settings": "设置",
        "quit": "退出",
        "easy": "简单",
        "standard": "标准",
        "hard": "困难",
        "start_battle": "开始战斗",
        "menu": "返回主菜单",
        "resume": "继续战斗",
        "restart": "重新开始",
        "back": "返回",
        "play_again": "再战",
        "retry": "重开",
        "language": "语言",
        "english": "English",
        "chinese": "简体中文",
        "sfx_volume": "音效音量",
        "music_volume": "音乐音量",
        "action_header": "行为",
        "key_header": "键位／输入",
        "action_move_up": "向上移动",
        "action_move_down": "向下移动",
        "action_move_left": "向左移动",
        "action_move_right": "向右移动",
        "action_missile": "追踪导弹",
        "action_arc": "连锁电弧",
        "action_support": "火力支援",
        "action_pause": "暂停／继续",
        "action_aim": "瞄准",
        "action_fire": "射击",
        "mouse_move": "鼠标移动",
        "mouse_left": "鼠标左键",
        "key_prompt": "请按下新键…",
        "edit_hint": "左键点击键位单元格，再按下一个键盘键。",
        "setup_hint": "前往设置页面修改键位。",
        "conflict_hint": "共享键位会触发所有对应行为。",
        "reset_keys": "重置键位",
        "save_failed": "设置未能保存；本次运行仍然生效。",
        "bgm_loaded": "已载入背景音乐",
        "bgm_missing": "尚未提供背景音乐，当前无音乐运行",
        "audio_unavailable": "音频设备不可用：静音运行",
        "rule_goal": "完成 12 波并击毁母舰即可获胜。",
        "rule_health": "生命归零时战斗失败。",
        "rule_supplies": "每 7 秒生成补给；满容量不消耗。",
        "rule_weapons": "特殊武器：三格充满，持续 5 秒。",
        "rule_support": "满能量呼叫五轮支援；支援中不回能。",
        "rule_focus": "失焦自动暂停；继续后需重新按射击键。",
        "boss_status": "外星母舰  {hp}/{max_hp}  阶段 {phase}",
        "phase_transition": "阶段转换",
        "boss_warning": "警告 — 外星母舰即将到达",
        "hp_score": "生命 {hp:3}  分数 {score}",
        "bullet": "基础子弹",
        "missile": "追踪导弹",
        "arc": "连锁电弧",
        "weapon_status": "{weapon}  {seconds:.1f}秒",
        "support_status": "支援 {seconds:.1f}秒",
        "wave_status": "第 {number}/12 波   {phase}",
        "waves": "敌群进攻",
        "rest": "波间休息",
        "meteor_clear": "清理陨石",
        "boss_approach": "母舰即将到达",
        "boss_entry": "母舰入场",
        "boss_fight": "母舰战斗",
        "paused": "战斗暂停 · {binding} 继续",
        "victory": "任务完成",
        "defeat": "任务失败",
        "result": "分数 {score}  /  击杀 {kills}  /  用时 {seconds:.1f}秒",
    },
}


def translate(language, key, **values):
    return TEXT[language][key].format(**values)
