"""界面文本集中管理；语言只影响显示，不改变规则或难度 ID。"""

DEFAULT_LANGUAGE = "en"

TEXT = {
    "en": {
        "title": "ALIEN INVASION",
        "window_title": "Alien Invasion",
        "levels_title": "Levels",
        "level_name": "Level {number}",
        "level_hint": "Choose a level to begin  |  1 / 2 / 3 to enter  |  Esc to return",
        "enter_level": "Enter Level",
        "difficulty": "Difficulty",
        "settings_title": "Settings",
        "tagline": "Survive 12 waves and defeat the alien mothership",
        "start_game": "Start Game",
        "settings": "Settings",
        "quit": "Quit",
        "easy": "Easy",
        "standard": "Standard",
        "hard": "Hard",
        "menu": "Main Menu",
        "resume": "Resume",
        "restart": "Restart",
        "back": "Back",
        "play_again": "Play Again",
        "retry": "Retry",
        "language": "Language",
        "english": "English",
        "chinese": "简体中文",
        "sfx_volume": "Sound Effects",
        "music_volume": "Music",
        "action_header": "Action",
        "key_header": "Key / Input",
        "action_move_up": "Move Up",
        "action_move_down": "Move Down",
        "action_move_left": "Move Left",
        "action_move_right": "Move Right",
        "action_missile": "Guided Missiles",
        "action_arc": "Chain Arc",
        "action_support": "Fire Support",
        "action_pause": "Pause / Resume",
        "action_aim": "Aim",
        "action_fire": "Fire",
        "mouse_move": "Mouse Movement",
        "mouse_left": "Left Mouse Button",
        "key_prompt": "Press any key...",
        "edit_hint": "Click a key cell, then press a keyboard key.",
        "conflict_hint": "Shared keys trigger all assigned actions.",
        "reset_keys": "Reset Key Bindings",
        "save_failed": "Could not save settings; changes apply for this run.",
        "bgm_loaded": "Background music loaded",
        "bgm_missing": "No background music provided",
        "audio_unavailable": "Audio device unavailable: sound muted",
        "rule_goal": "Clear 12 waves and defeat the mothership.",
        "rule_health": "Zero health ends the mission.",
        "rule_supplies": "Supplies every 7s; full capacity keeps them.",
        "rule_weapons": "Special weapons: 3 charges, 5s duration.",
        "rule_support": "Full energy: 5 strikes; no recharge during support.",
        "rule_focus": "Focus loss pauses; press fire again after resuming.",
        "boss_status": "MOTHERSHIP  {hp}/{max_hp}  PHASE {phase}",
        "phase_transition": "PHASE TRANSITION",
        "boss_warning": "WARNING - MOTHERSHIP APPROACHING",
        "hp_score": "HP {hp:3}  Score {score}",
        "bullet": "Basic Bullets",
        "missile": "Guided Missiles",
        "arc": "Chain Arc",
        "weapon_status": "{weapon}  {seconds:.1f}s",
        "support_status": "Support {seconds:.1f}s",
        "wave_status": "LEVEL {level}   WAVE {number}/12   {phase}",
        "waves": "ENEMY WAVES",
        "rest": "WAVE BREAK",
        "meteor_clear": "CLEARING METEORS",
        "boss_approach": "BOSS APPROACHING",
        "boss_entry": "BOSS ENTRY",
        "boss_fight": "BOSS FIGHT",
        "paused": "Mission Paused - {binding} to Resume",
        "victory": "Mission Complete",
        "defeat": "Mission Failed",
        "result": "Score {score}  /  Kills {kills}  /  Time {seconds:.1f}s",
        "tutorial_label": "Flight Training - fixed difficulty",
        "level_2_note": "12 waves and the mothership",
        "level_3_note": "+20% enemies / +40% Boss HP",
        "tutorial_status": "TRAINING {step}/8  -  {title}",
        "tutorial_continue": "Continue",
        "tutorial_complete": "Training Complete",
        "tutorial_retry": "Try This Step Again",
        "tutorial_retry_button": "Retry Current Step",
        "tutorial_restart": "Restart Training",
        "tutorial_levels": "Back to Levels",
        "tutorial_go_level_2": "Choose Level 2 Difficulty",
        "tutorial_summary": "8/8 completed  /  Time {seconds:.1f}s  /  Retries {count}",
        "tutorial_title_1": "Movement",
        "tutorial_title_2": "Aim and Fire",
        "tutorial_title_3": "Dodge Meteors",
        "tutorial_title_4": "Health Supplies",
        "tutorial_title_5": "Guided Missiles",
        "tutorial_title_6": "Chain Arc",
        "tutorial_title_7": "Fire Support",
        "tutorial_title_8": "Combat Practice",
        "tutorial_move": "Move: {move_up} up, {move_left} left, {move_down} down, {move_right} right.",
        "tutorial_move_note": "Movement follows the screen; the mouse turns your ship. Try freely, then click Continue.",
        "tutorial_shoot": "Move the mouse to aim at the training target. Hold the left mouse button to fire.",
        "tutorial_release": "Release the left mouse button to stop firing.",
        "tutorial_aim": "Move the mouse onto the remaining aim marker, then release fire.",
        "tutorial_targets": "Targets destroyed: {count}/{total}",
        "tutorial_dodge": "Watch the warning lane, then move sideways. Dodge the meteor without shooting it.",
        "tutorial_dodges": "Meteors dodged: {count}/3",
        "tutorial_health": "Training preset: HP 75. Fly into the marked health supply to restore 25 HP.",
        "tutorial_supply_types": "Health: +25 HP. Missile / Arc: +1 charge. Full capacity keeps the supply.",
        "tutorial_charge": "Collect 3 {weapon} supplies to fill the three charge boxes.",
        "tutorial_use_missile": "Press {binding}, then hold left mouse to fire a guided missile at a moving target.",
        "tutorial_missile_note": "Missiles replace bullets for 5 seconds. Releasing fire does not stop the timer.",
        "tutorial_use_arc": "Move near the formation, aim upward, press {binding}, then hold left mouse.",
        "tutorial_arc_note": "Arc range: 300 pixels; jumps: 130 pixels. Hit 3 targets in one chain.",
        "tutorial_wait_weapon": "Successful hit! Observe the full 5 seconds and the return to basic bullets.",
        "tutorial_energy": "Use basic bullets to destroy 5 heavy training targets and build combat energy.",
        "tutorial_energy_note": "Actual damage + kills build energy. This meter is separate from weapon charges.",
        "tutorial_support_ready": "Energy full! Release fire and press {binding} to call off-screen support.",
        "tutorial_support_active": "Watch all 5 support rounds. Energy stays empty during the 7.5-second support.",
        "tutorial_support_rounds": "Support rounds: {count}/5  -  up to 3 targets per round",
        "tutorial_combat_note": "Fight independently. Collect supplies and use skills when ready. Survive both waves.",
        "tutorial_combat_wave": "Combat wave {number}/2  -  enemy cap 2",
        "tutorial_reset": "Training checkpoint restored. Press movement / fire again when ready.",
        "tutorial_step_done": "Step complete! Preparing the next exercise...",
        "tutorial_meteor_hit": "Meteor collision. Watch the warning lane and move sideways. Retrying this meteor.",
        "tutorial_meteor_shot": "You destroyed the meteor. This exercise needs a dodge. Retrying this meteor.",
        "tutorial_meteor_move": "Move at least 70 pixels sideways after the warning. Retrying this meteor.",
        "tutorial_skill_retry": "No successful skill hit. Collect the supplies and try this exercise again.",
        "tutorial_support_retry": "No support hit observed. Build energy and try the support exercise again.",
        "tutorial_help_2": "Move the crosshair onto the marked target and hold left click. Release left click after all 3 targets.",
        "tutorial_help_3": "Watch the warning lane. Use {move_left} / {move_right} to move sideways; let the meteor leave intact.",
        "tutorial_help_4": "Fly into the health supply marked by the arrow. It restores your training health from 75 to 100.",
        "tutorial_help_5": "Collect 3 missile supplies, press {missile}, then hold left click to hit a target. Wait for bullets to return.",
        "tutorial_help_6": "Collect 3 arc supplies, approach the formation, aim up, press {arc} and hold left click to chain 3 targets.",
        "tutorial_help_7": "Shoot 5 heavy training targets to fill energy, then press {support}. Watch all 5 support rounds finish.",
        "tutorial_help_8": "Keep moving and shoot the enemies. You may use charged weapons; only survival through both waves is required.",
        "tutorial_combat_health_hint": "Health is low. Avoid contact and collect a health supply when one appears.",
        "tutorial_combat_fire_hint": "Enemy bullets are live now. Keep moving while aiming and shooting.",
        "tutorial_combat_skill_hint": "A weapon is charged. Use {missile} for missiles or {arc} for arc when its three boxes are full, then hold left click.",
        "tutorial_combat_support_hint": "Support energy is full. Press {support} to call five support rounds.",
        "tutorial_conflict": "Opposite movement keys cancel out. Open Settings to fix the bindings.",
        "tutorial_pause_hint": "{binding}: pause  /  Settings: language, volume and key bindings",
    },
    "zh-CN": {
        "title": "外星入侵",
        "window_title": "外星入侵",
        "levels_title": "关卡",
        "level_name": "关卡 {number}",
        "level_hint": "选择关卡开始战斗  |  1 / 2 / 3 进入关卡  |  Esc 返回",
        "enter_level": "进入关卡",
        "difficulty": "难度",
        "settings_title": "设置",
        "tagline": "生存 · 12 波敌群 · 外星母舰",
        "start_game": "开始游戏",
        "settings": "设置",
        "quit": "退出",
        "easy": "简单",
        "standard": "标准",
        "hard": "困难",
        "menu": "返回主菜单",
        "resume": "继续战斗",
        "restart": "重新开始",
        "back": "返回",
        "play_again": "再战",
        "retry": "重开",
        "language": "语言",
        "english": "English",
        "chinese": "简体中文",
        "sfx_volume": "音效音量",
        "music_volume": "音乐音量",
        "action_header": "行为",
        "key_header": "键位／输入",
        "action_move_up": "向上移动",
        "action_move_down": "向下移动",
        "action_move_left": "向左移动",
        "action_move_right": "向右移动",
        "action_missile": "追踪导弹",
        "action_arc": "连锁电弧",
        "action_support": "火力支援",
        "action_pause": "暂停／继续",
        "action_aim": "瞄准",
        "action_fire": "射击",
        "mouse_move": "鼠标移动",
        "mouse_left": "鼠标左键",
        "key_prompt": "请按下新键…",
        "edit_hint": "左键点击键位单元格，再按下一个键盘键。",
        "conflict_hint": "共享键位会触发所有对应行为。",
        "reset_keys": "重置键位",
        "save_failed": "设置未能保存；本次运行仍然生效。",
        "bgm_loaded": "已载入背景音乐",
        "bgm_missing": "尚未提供背景音乐，当前无音乐运行",
        "audio_unavailable": "音频设备不可用：静音运行",
        "rule_goal": "完成 12 波并击毁母舰即可获胜。",
        "rule_health": "生命归零时战斗失败。",
        "rule_supplies": "每 7 秒生成补给；满容量不消耗。",
        "rule_weapons": "特殊武器：三格充满，持续 5 秒。",
        "rule_support": "满能量呼叫五轮支援；支援中不回能。",
        "rule_focus": "失焦自动暂停；继续后需重新按射击键。",
        "boss_status": "外星母舰  {hp}/{max_hp}  阶段 {phase}",
        "phase_transition": "阶段转换",
        "boss_warning": "警告 — 外星母舰即将到达",
        "hp_score": "生命 {hp:3}  分数 {score}",
        "bullet": "基础子弹",
        "missile": "追踪导弹",
        "arc": "连锁电弧",
        "weapon_status": "{weapon}  {seconds:.1f}秒",
        "support_status": "支援 {seconds:.1f}秒",
        "wave_status": "关卡 {level}   第 {number}/12 波   {phase}",
        "waves": "敌群进攻",
        "rest": "波间休息",
        "meteor_clear": "清理陨石",
        "boss_approach": "母舰即将到达",
        "boss_entry": "母舰入场",
        "boss_fight": "母舰战斗",
        "paused": "战斗暂停 · {binding} 继续",
        "victory": "任务完成",
        "defeat": "任务失败",
        "result": "分数 {score}  /  击杀 {kills}  /  用时 {seconds:.1f}秒",
        "tutorial_label": "新手训练 · 固定训练难度",
        "level_2_note": "12 波敌群与母舰战",
        "level_3_note": "敌机总量 +20%／Boss 生命 +40%",
        "tutorial_status": "训练 {step}/8  ·  {title}",
        "tutorial_continue": "继续",
        "tutorial_complete": "训练完成",
        "tutorial_retry": "重试当前训练步骤",
        "tutorial_retry_button": "重试当前步骤",
        "tutorial_restart": "重新训练",
        "tutorial_levels": "返回关卡",
        "tutorial_go_level_2": "选择关卡 2 的难度",
        "tutorial_summary": "已完成 8/8  /  用时 {seconds:.1f}秒  /  重试 {count} 次",
        "tutorial_title_1": "WASD 移动",
        "tutorial_title_2": "瞄准与开火",
        "tutorial_title_3": "躲避陨石",
        "tutorial_title_4": "回血补给",
        "tutorial_title_5": "追踪导弹",
        "tutorial_title_6": "连锁电弧",
        "tutorial_title_7": "火力支援",
        "tutorial_title_8": "综合实战",
        "tutorial_move": "移动：{move_up} 向上，{move_left} 向左，{move_down} 向下，{move_right} 向右。",
        "tutorial_move_note": "移动方向按屏幕计算，鼠标控制朝向。可自由尝试，点击“继续”进入下一步。",
        "tutorial_shoot": "移动鼠标瞄准训练靶机，按住鼠标左键持续开火。",
        "tutorial_release": "松开鼠标左键，停止发射新子弹。",
        "tutorial_aim": "移动鼠标到瞄准标记附近，然后松开左键。",
        "tutorial_targets": "已击毁靶机：{count}/{total}",
        "tutorial_dodge": "观察预警落点带，向侧面移动，躲开陨石。这次练习不要击碎陨石。",
        "tutorial_dodges": "成功躲避：{count}/3",
        "tutorial_health": "训练预设：生命 75。驶向箭头标记的回血补给，恢复 25 点生命。",
        "tutorial_supply_types": "回血 +25；导弹／电弧各 +1 格充能。满血或满充能时不会消耗对应补给。",
        "tutorial_charge": "收集三份{weapon}补给，点亮三格充能。",
        "tutorial_use_missile": "按 {binding} 激活导弹，再按住左键，命中移动靶机。",
        "tutorial_missile_note": "导弹替换子弹 5 秒。松开左键不会停止计时。",
        "tutorial_use_arc": "靠近编队，向上瞄准，按 {binding} 激活电弧，再按住左键。",
        "tutorial_arc_note": "首目标范围 300 像素，跳跃范围 130 像素。一次连到三个不同靶机。",
        "tutorial_wait_weapon": "命中成功！观察完整 5 秒结束，并恢复基础子弹。",
        "tutorial_energy": "使用基础子弹击毁五架重型训练靶机，积攒战斗能量。",
        "tutorial_energy_note": "实际伤害与击毁奖励积攒能量；这条能量与武器补给充能分开。",
        "tutorial_support_ready": "能量已满！松开左键，按 {binding} 呼叫场外支援。",
        "tutorial_support_active": "观察完整五轮支援。支援持续 7.5 秒，期间能量保持为零。",
        "tutorial_support_rounds": "支援轮次：{count}/5  ·  每轮最多三个不同目标",
        "tutorial_combat_note": "自由实战，拾取补给，充满后自主使用技能。存活并完成两波即可通过。",
        "tutorial_combat_wave": "实战第 {number}/2 波  ·  场内敌机上限 2",
        "tutorial_reset": "训练检查点已恢复。准备好后重新按下移动／射击键。",
        "tutorial_step_done": "本步完成！正在准备下一项训练…",
        "tutorial_meteor_hit": "碰到陨石了。先看落点，再向侧面移动。重试当前陨石，保留已成功次数。",
        "tutorial_meteor_shot": "陨石被击碎了，本次需要移动躲避。重试当前陨石。",
        "tutorial_meteor_move": "预警后向侧面移动至少 70 像素。重试当前陨石。",
        "tutorial_skill_retry": "尚未完成技能命中。重新收集训练补给，再试一次。",
        "tutorial_support_retry": "尚未观察到支援命中。重新积攒能量，练习呼叫支援。",
        "tutorial_help_2": "把准星移到标记靶机上，按住左键开火。击毁三架后松开左键。",
        "tutorial_help_3": "先看预警带，使用 {move_left}／{move_right} 向侧面移开，让陨石完整离场。",
        "tutorial_help_4": "驶向箭头标记的回血补给，接触后训练生命会从 75 恢复到 100。",
        "tutorial_help_5": "收集三份导弹补给，按 {missile}，再按住左键命中靶机；等待恢复子弹。",
        "tutorial_help_6": "收集三份电弧补给，靠近编队，向上瞄准，按 {arc} 和左键，一次连到三架靶机。",
        "tutorial_help_7": "用子弹击毁五架重型训练靶机充满能量，按 {support}，观察完整五轮支援。",
        "tutorial_help_8": "持续移动并瞄准射击，可自主使用充满的武器。存活并完成两波即可。",
        "tutorial_combat_health_hint": "生命较低，避开碰撞；回血补给出现后可拾取恢复生命。",
        "tutorial_combat_fire_hint": "敌机开始发射真实子弹，瞄准射击时保持移动。",
        "tutorial_combat_skill_hint": "武器已充满，导弹用 {missile}，电弧用 {arc}；对应三格全亮时激活，再按住左键。",
        "tutorial_combat_support_hint": "支援能量已满，按 {support} 呼叫五轮支援。",
        "tutorial_conflict": "相反移动方向绑定了同一个键，会互相抵消。可打开设置修改。",
        "tutorial_pause_hint": "{binding}：暂停  /  设置：语言、音量与键位",
    },
}


def translate(language, key, **values):
    return TEXT[language][key].format(**values)
